#
# Generated by xwot compiler.
#
# Flask xwot application.
#
# Type:       xwot:Resource
# Resource:   DoorResource
# Path:       /door
#

from flask import request
from xwot.util.flask import make_response
from xwot.util import deserialize
from xwot.device.door import Door
from xwot_app import app

door = Door(name='xWoT Door', street_address="Bd de Perolles 90 - DEPARTEMENT D'INFORMATIQUE",
            postal_code='1700', address_locality='Fribourg', room_address='A410')

#
# GET '/door'
#
@app.route('/door', methods=['GET'])
def handle_door_GET():
    return make_response(door)

#
# PUT '/door'
#
@app.route('/door', methods=['PUT'])
def handle_door_PUT():
    data = request.data
    content_type = request.headers.get('Content-Type')
    dic = deserialize(data, content_type)
    door.update(dic, content_type)

    return make_response(door)


