#
# Generated by xwot compiler.
#
# Flask xwot application.
#
# Type:       xwot:Resource
# Resource:   DoorResource
# Path:       /door
#

from flask import request
from xwot_app import app


#
# GET '/door'
#
@app.route('/door', methods=['GET'])
def handle_door_GET():
    return "Name: DoorResource , Hello at: /door"

#
# POST '/door'
#
@app.route('/door', methods=['POST'])
def handle_door_POST():
    return "Name: DoorResource , Hello at: /door"

#
# PUT '/door'
#
@app.route('/door', methods=['PUT'])
def handle_door_PUT():
    return "Name: DoorResource , Hello at: /door"

#
# DELETE '/door'
#
@app.route('/door', methods=['DELETE'])
def handle_door_DELETE():
    return "Name: DoorResource , Hello at: /door"

