#
# Generated by xwot compiler.
#
# Flask xwot application.
#
# Type:       xwot:ContextResource
# Resource:   LockResource
# Path:       /door/lock
#

from flask import request
from xwot_app import app


#
# GET '/door/lock'
#
@app.route('/door/lock', methods=['GET'])
def handle_door_lock_GET():
    return "Name: LockResource , Hello at: /door/lock"

#
# POST '/door/lock'
#
@app.route('/door/lock', methods=['POST'])
def handle_door_lock_POST():
    return "Name: LockResource , Hello at: /door/lock"

#
# PUT '/door/lock'
#
@app.route('/door/lock', methods=['PUT'])
def handle_door_lock_PUT():
    return "Name: LockResource , Hello at: /door/lock"

