#
# Generated by xwot compiler.
#
# Klein xwot application.
#
# Type:       xwot:ContextResource
# Resource:   LockResource
# Path:       /door/lock
#

from xwot.util.klein import make_response
from xwot.util import deserialize
from xwot.device.door import Lock
from xwot_app import app

lock = Lock(name='Door lock')

#
# GET '/door/lock'
#
@app.route('/door/lock', methods=['GET'])
def handle_door_lock_GET(request):
    return make_response(lock, request)

#
# PUT '/door/lock'
#
@app.route('/door/lock', methods=['PUT'])
def handle_door_lock_PUT(request):
    data = request.content.read()
    content_type = request.getHeader('Content-Type')
    dic = deserialize(data, content_type)
    lock.update(dic, content_type)

    return make_response(lock, request)

