#
# Generated by xwot compiler.
#
# Flask xwot application.
#
# Type:       xwot:ContextResource
# Resource:   LockResource
# Path:       /door/lock
#

from flask import request
from xwot.util.flask import make_response
from xwot.util import deserialize
from xwot.device.door import Lock
from xwot_app import app

lock = Lock(name='Door lock')

#
# GET '/door/lock'
#
@app.route('/door/lock', methods=['GET'])
def handle_door_lock_GET():
    return make_response(lock)

#
# PUT '/door/lock'
#
@app.route('/door/lock', methods=['PUT'])
def handle_door_lock_PUT():
    data = request.data
    content_type = request.headers.get('Content-Type')
    dic = deserialize(data, content_type)
    lock.update(dic, content_type)

    return make_response(lock)

