#
# Generated by xwot compiler.
#
# Klein xwot application.
#
# Type:       xwot:SensorResource
# Resource:   AltitudeResource
# Path:       /weatherstation/sensors/altitude
#

from xwot_app import app
from xwot.util.klein import make_response
from . import sensors_dic

altitude_sensor = sensors_dic['altitude']


#
# GET '/weatherstation/sensors/altitude'
#
@app.route('/weatherstation/sensors/altitude', methods=['GET'])
def handle_weatherstation_sensors_altitude_GET(request):
    return make_response(altitude_sensor, request)

