#
# Generated by xwot compiler.
#
# Flask xwot application.
#
# Type:       xwot:SensorResource
# Resource:   ColorResource
# Path:       /weatherstation/sensors/color
#

from xwot_app import app
from xwot.util.flask import make_response
from . import sensors_dic

color_sensor = sensors_dic['color']

#
# GET '/weatherstation/sensors/color'
#
@app.route('/weatherstation/sensors/color', methods=['GET'])
def handle_weatherstation_sensors_color_GET():
    return make_response(color_sensor)

