#
# Generated by xwot compiler.
#
# Flask xwot application.
#
# Type:       xwot:SensorResource
# Resource:   IlluminanceResource
# Path:       /weatherstation/sensors/illuminance
#

from xwot_app import app
from xwot.util.flask import make_response
from . import sensors_dic

illuminance_sensor = sensors_dic['illuminance']


#
# GET '/weatherstation/sensors/illuminance'
#
@app.route('/weatherstation/sensors/illuminance', methods=['GET'])
def handle_weatherstation_sensors_illuminance_GET():
    return make_response(illuminance_sensor)

