#
# Generated by xwot compiler.
#
# Flask xwot application.
#
# Type:       xwot:SensorResource
# Resource:   PressureResource
# Path:       /weatherstation/sensors/pressure
#


from xwot_app import app
from xwot.util.flask import make_response
from . import sensors

pressure_sensor = sensors['pressure']

#
# GET '/weatherstation/sensors/pressure'
#
@app.route('/weatherstation/sensors/pressure', methods=['GET'])
def handle_weatherstation_sensors_pressure_GET():
    return make_response(pressure_sensor)

