#
# Generated by xwot compiler.
#
# Klein xwot application.
#
# Type:       xwot:Resource
# Resource:   SensorsResource
# Path:       /weatherstation/sensors
#

from xwot_app import app
from xwot.util.klein import make_response
from . import sensor_collection

#
# GET '/weatherstation/sensors'
#
@app.route('/weatherstation/sensors', methods=['GET'])
def handle_weatherstation_sensors_GET(request):
    return make_response(sensor_collection, request)
