#
# Generated by xwot compiler.
#
# Flask xwot application.
#
# Type:       xwot:Resource
# Resource:   SensorsResource
# Path:       /weatherstation/sensors
#

from flask import request
from xwot_app import app
from xwot.util.flask import make_response
from . import sensor_collection

#
# GET '/weatherstation/sensors'
#
@app.route('/weatherstation/sensors', methods=['GET'])
def handle_weatherstation_sensors_GET():
    return make_response(sensor_collection)
