#
# Generated by xwot compiler.
#
# Flask xwot application.
#
# Type:       xwot:Resource
# Resource:   WeatherstationResource
# Path:       /weatherstation
#

from flask import request
from xwot_app import app
from . import weatherstation
from xwot.util.flask import make_response


#
# GET '/weatherstation'
#
@app.route('/weatherstation', methods=['GET'])
def handle_weatherstation_GET():
    return make_response(weatherstation)


#
# POST '/weatherstation'
#
@app.route('/weatherstation', methods=['POST'])
def handle_weatherstation_POST():
    return "Name: WeatherstationResource , Hello at: /weatherstation"

#
# PUT '/weatherstation'
#
@app.route('/weatherstation', methods=['PUT'])
def handle_weatherstation_PUT():
    return "Name: WeatherstationResource , Hello at: /weatherstation"

#
# DELETE '/weatherstation'
#
@app.route('/weatherstation', methods=['DELETE'])
def handle_weatherstation_DELETE():
    return "Name: WeatherstationResource , Hello at: /weatherstation"

