#
# Generated by xwot compiler.
#
# Flask xwot application.
#
# Type:       xwot:Resource
# Resource:   WeatherstationResource
# Path:       /weatherstation
#

from flask import request
from xwot_app import app
from . import weatherstation
from xwot.util import deserialize
from xwot.util.flask import make_response


#
# GET '/weatherstation'
#
@app.route('/weatherstation', methods=['GET'])
def handle_weatherstation_GET():
    return make_response(weatherstation)

#
# PUT '/weatherstation'
#
@app.route('/weatherstation', methods=['PUT'])
def handle_weatherstation_PUT():
    data = request.data
    content_type = request.headers.get('Content-Type')
    dic = deserialize(data, content_type)
    status = weatherstation.update(dic, content_type)

    return make_response(weatherstation, status=status)


