# coding: utf-8
#
# Generated by xwot compiler.
#
# Klein xwot application.
#
# Type:       xwot:SensorResource
# Resource:   TemperatureSensorResource
# Path:       /sensing-device/temperature
#

from xwot_app import app
from xwot.util.klein import make_response
from model import TemperatureSensor
from xwot.util.klein import cors

temperature_sensor = TemperatureSensor()

#
# GET '/sensor/temperature'
#
@app.route('/sensing-device/temperature', methods=['GET'])
def handle_sensor_temperature_GET(request):
    cors(request, methods=['GET'])
    return make_response(temperature_sensor, request)

