#
# Generated by xwot compiler.
#
# Klein xwot application.
#
# Type:       xwot:SensorResource
# Resource:   HumidityResource
# Path:       /weatherstation/sensors/humidity
#

from xwot_app import app
from xwot.util.klein import make_response
from xwot.util.klein import cors
from . import sensors_dic

humidity_sensor = sensors_dic['humidity']

#
# GET '/weatherstation/sensors/humidity'
#
@app.route('/weatherstation/sensors/humidity', methods=['GET'])
def handle_weatherstation_sensors_humidity_GET(request):
    cors(request, methods=['GET'])
    return make_response(humidity_sensor, request)

