#
# Generated by xwot compiler.
#
# Klein xwot application.
#
# Type:       xwot:SensorResource
# Resource:   Temperature1Resource
# Path:       /weatherstation/sensors/temperature1
#

from xwot_app import app
from xwot.util.klein import make_response
from xwot.util.klein import cors
from . import sensors_dic

temperature_1 = sensors_dic['temperature_1']

#
# GET '/weatherstation/sensors/temperature1'
#
@app.route('/weatherstation/sensors/temperature1', methods=['GET'])
def handle_weatherstation_sensors_temperature1_GET(request):
    cors(request, methods=['GET'])
    return make_response(temperature_1, request)

