#
# Generated by xwot compiler.
#
# Klein xwot application.
#
# Type:       xwot:ContextResource
# Resource:   ShutterResource
# Path:       /window/shutter
#

from xwot_app import app
from xwot.device.shutter import Shutter
from xwot.util.klein import make_response
from xwot.util import deserialize
from xwot.util.klein import cors

shutter = Shutter('Window shutter')


#
# GET '/window/shutter'
#
@app.route('/window/shutter', methods=['GET'])
def handle_window_shutter_GET(request):
    cors(request, methods=['GET', 'PUT'])
    return make_response(shutter, request)


#
# PUT '/window/shutter'
#
@app.route('/window/shutter', methods=['PUT'])
def handle_window_shutter_PUT(request):
    data = request.content.read()
    content_type = request.getHeader('Content-Type')
    dic = deserialize(data, content_type=content_type)
    shutter.update(dic, content_type)
    cors(request, methods=['GET', 'PUT'])
    return make_response(shutter, request)

