#
# Generated by xwot compiler.
#
# Klein xwot application.
#
# Type:       xwot:DeviceResource
# Resource:   GPSResource
# Path:       /weatherstation/gps
#

from xwot.util.klein import make_response
from xwot_app import app
from . import gps


#
# GET '/weatherstation/gps'
#
@app.route('/weatherstation/gps', methods=['GET'])
def handle_weatherstation_gps_GET(request):
    return make_response(gps, request)

