#
# Generated by xwot compiler.
#
# Flask xwot application.
#
# Type:       xwot:Resource
# Resource:   DHT22Resource
# Path:       /dht22
#

from flask import request
from xwot_app import app
from xwot.model import Device, BaseModel
from xwot.util.flask import make_response
from xwot.util import deserialize

class DHT22(Device,BaseModel):


    __mutable_props__ = ["roomAddress"]
    __expose__ = __mutable_props__ + ["name", "description", "temperature", "humidity"]
    def __init__(self):
        super(DHT22,self).__init__()
        self.add_link("temperature")
        self.add_link("humidity")
        self._dic = {"roomAddress": "Bureau C412"}

    @property
    def resource_path(self):
        return "/dht22"

    @property
    def name(self):
        return "dht22-device"

    @property
    def description(self):
        return "temperature and humidity sensor"

    @property
    def temperature(self):
        return "/dht22/temperature"

    @property
    def humidity(self):
        return "/dht22/humidity"

    @property
    def roomAddress(self):
        return self._dic["roomAddress"]

dht = DHT22()

#
# GET '/dht22'
#
@app.route('/dht22', methods=['GET'])
def handle_dht22_GET():
    return make_response(dht)

#
# PUT '/dht22'
#
@app.route('/dht22', methods=['PUT'])
def handle_dht22_PUT():
    data = request.data
    content_type = request.headers.get("Content-Type")
    dic = deserialize(data, content_type)
    dht.update(dic, content_type)
    return make_response(dht)


