#
# Generated by xwot compiler.
#
# Flask xwot application.
#
# Type:       xwot:Entity
# Resource:   Entity
# Path:       /
#

import xwot_app
from xwot_app import app
from xwot.util.klein import make_response
from xwot.util.klein import cors
from twisted.web.static import File


@app.route('/')
def home(request):
    request.setHeader('Content-Type', 'application/ld+json')
    cors(request, methods=['GET'])
    return xwot_app.jsonld_description_str

#
# OPTIONS '/'
#
@app.route('/', methods=['OPTIONS'])
def home_OPTIONS(request):
    cors(request, methods=['GET', 'OPTIONS'])
    request.setHeader('Allow', 'GET')

@app.route('/static/', branch=True)
def static_files(request):
    return File("./static")
