#
# Generated by xwot compiler.
#
# Flask xwot application.
#
# Type:       xwot:PublisherResource
# Resource:   HumidityResourcePublisherResource
# Path:       /dht22/humidity/pub
#

from flask import request
from xwot_app import app


#
# GET '/dht22/humidity/pub'
#
@app.route('/dht22/humidity/pub', methods=['GET'])
def handle_dht22_humidity_pub_GET():
    return "Name: HumidityResourcePublisherResource , Hello at: /dht22/humidity/pub"

#
# POST '/dht22/humidity/pub'
#
@app.route('/dht22/humidity/pub', methods=['POST'])
def handle_dht22_humidity_pub_POST():
    return "Name: HumidityResourcePublisherResource , Hello at: /dht22/humidity/pub"

