#
# Generated by xwot compiler.
#
# Flask xwot application.
#
# Type:       xwot:PublisherResource
# Resource:   TemperatureResourcePublisherResource
# Path:       /dht22/temperature/pub
#

from flask import request
from xwot_app import app


#
# GET '/dht22/temperature/pub'
#
@app.route('/dht22/temperature/pub', methods=['GET'])
def handle_dht22_temperature_pub_GET():
    return "Name: TemperatureResourcePublisherResource , Hello at: /dht22/temperature/pub"

#
# POST '/dht22/temperature/pub'
#
@app.route('/dht22/temperature/pub', methods=['POST'])
def handle_dht22_temperature_pub_POST():
    return "Name: TemperatureResourcePublisherResource , Hello at: /dht22/temperature/pub"

