#
# Generated by xwot compiler.
#
# Klein xwot application.
#
# Type:       xwot:Resource
# Resource:   LightbulbResource
# Path:       /room/lightbulb
#

import xwot_app
from xwot_app import app
import treq
import json
from xwot.model import Device as XWOTDevice
from xwot.model import BaseModel
from xwot.util import deserialize


class LightBulb(XWOTDevice, BaseModel):

    __mutable_props__ = ['name']
    __expose__ = __mutable_props__ + ['switch_link', 'sensor_link', 'room_link', 'description']

    def __init__(self):
        super(LightBulb, self).__init__()
        self._dic = {
            'name': None,
            'description': None
        }
        self._proxy_dic = {}
        self.add_type('xwot-ext:LightBulb')
        self.add_link('room_link')
        self.add_link('switch_link')
        self.add_link('sensor_link')

    @property
    def resource_path(self):
        return '/room/lightbulb'

    @property
    def name(self):
        return self._dic['name']

    @property
    def description(self):
        return self._dic['description']

    @property
    def room_link(self):
        return '/room'

    @property
    def switch_link(self):
        return '/room/lightbulb/switch'

    @property
    def sensor_link(self):
        return '/room/lightbulb/sensor'

    @property
    def state(self):
        return self._dic['state']

    def parse(self, data, accept):
        dic = json.loads(data)
        self._proxy_dic = dic
        self._dic['name'] = self._proxy_dic.get('name', None)
        self._dic['description'] = self._proxy_dic.get('description', None)
        return accept

    def serialize(self, content_type):
        if content_type == 'application/json':
            return self.to_json()

        if content_type == 'application/ld+json':
            return self.to_jsonld()

        if content_type == 'application/xml':
            return self.to_xml()

        return None

lightbulb = LightBulb()

#
# GET '/room/lightbulb'
#
@app.route('/room/lightbulb', methods=['GET'])
def handle_room_lightbulb_GET(request):
    if xwot_app.resources['lightbulb']:
        accept = request.getHeader('Accept')
        d = treq.get(xwot_app.resources['lightbulb'], headers={'Accept': 'application/json'})
        request.setHeader('Content-Type', accept)
        d.addCallback(treq.content)
        d.addCallback(lightbulb.parse, accept)
        d.addCallback(lightbulb.serialize)

        return d
    else:
        request.setResponseCode(404)
    return ''

#
# PUT '/room/lightbulb'
#
@app.route('/room/lightbulb', methods=['PUT'])
def handle_room_lightbulb_PUT(request):
    if xwot_app.resources['lightbulb']:
        data = request.content.read()
        content_type = request.getHeader('Content-Type')
        dic = deserialize(data, content_type)
        lightbulb.update(dic, content_type)
        _data = lightbulb.serialize('application/json')

        accept = request.getHeader('Accept')
        d = treq.put(xwot_app.resources['lightbulb'], data=_data, headers={'Content-Type': 'application/json'})
        request.setHeader('Content-Type', accept)
        d.addCallback(treq.content)

        return lightbulb.serialize(accept)
    else:
        request.setResponseCode(404)
    return ''

