#
# Generated by xwot compiler.
#
# Klein xwot application.
#
# Type:       xwot:Resource
# Resource:   RoomResource
# Path:       /room
#

from xwot_app import app


#
# GET '/room'
#
@app.route('/room', methods=['GET'])
def handle_room_GET(request):
    return "Name: RoomResource , Hello at: /room"

#
# PUT '/room'
#
@app.route('/room', methods=['PUT'])
def handle_room_PUT(request):
    return "Name: RoomResource , Hello at: /room"

