#
# Generated by xwot compiler.
#
# Klein xwot application.
#
# Type:       xwot:ServiceResource
# Resource:   SwitchResource
# Path:       /room/lightbulb/switch
#

import xwot_app
from xwot_app import app
import treq
import json
from xwot.model import Service as XWOTService
from xwot.model import BaseModel
from xwot.util import deserialize


class Switch(XWOTService, BaseModel):

    __mutable_props__ = ['name', 'state', 'description']
    __expose__ = __mutable_props__ + ['lightbulb_link', 'room_link']

    def __init__(self):
        super(Switch, self).__init__()
        self._dic = {
            'name': None,
            'description': None,
            'state': None
        }
        self._proxy_dic = {}
        self.add_type('xwot-ext:Switch')
        self.add_link('room_link')
        self.add_link('lightbulb_link')

    @property
    def state(self):
        return self._dic['state']

    @property
    def name(self):
        return self._dic['name']

    @property
    def description(self):
        return self._dic['description']

    @property
    def room_link(self):
        return '/room'

    @property
    def lightbulb_link(self):
        return '/room/lightbulb'

    @property
    def state(self):
        return self._dic['state']

    def parse(self, data, accept):
        dic = json.loads(data)
        self._proxy_dic = dic
        self._dic['state'] = self._proxy_dic.get('state', None)
        self._dic['name'] = self._proxy_dic.get('name', None)
        self._dic['description'] = self._proxy_dic.get('description', None)
        return accept

    def serialize(self, content_type):
        if content_type == 'application/json':
            return self.to_json()

        if content_type == 'application/ld+json':
            return self.to_jsonld()

        if content_type == 'application/xml':
            return self.to_xml()

        return None

switch = Switch()

#
# GET '/room/lightbulb/switch'
#
@app.route('/room/lightbulb/switch', methods=['GET'])
def handle_room_lightbulb_switch_GET(request):
    if xwot_app.resources['lightbulb_switch']:
        accept = request.getHeader('Accept')
        d = treq.get(xwot_app.resources['lightbulb_switch'], headers={'Accept': 'application/json'})
        request.setHeader('Content-Type', accept)
        d.addCallback(treq.content)
        d.addCallback(switch.parse, accept)
        d.addCallback(switch.serialize)

        return d
    else:
        request.setResponseCode(404)
    return ''

#
# PUT '/room/lightbulb/switch'
#
@app.route('/room/lightbulb/switch', methods=['PUT'])
def handle_room_lightbulb_switch_PUT(request):
    if xwot_app.resources['lightbulb_switch']:
        data = request.content.read()
        content_type = request.getHeader('Content-Type')
        dic = deserialize(data, content_type)
        switch.update(dic, content_type)
        _data = switch.serialize('application/json')

        accept = request.getHeader('Accept')
        d = treq.put(xwot_app.resources['lightbulb_switch'], data=_data, headers={'Content-Type': 'application/json'})
        request.setHeader('Content-Type', accept)
        d.addCallback(treq.content)

        return switch.serialize(accept)
    else:
        request.setResponseCode(404)
    return ''


