#
# Generated by xwot compiler.
#
# Type:       xwot:SensorResource
# Resource:   Sensor
# Path:       /waterdispenser/sensor
#

from xwot_app import app

from xwot.util.klein import make_response
from xwot.util import deserialize
from xwot.device.waterdispenser import Sensor
from xwot.util.klein import cors

sensor = Sensor()

#
# GET '/waterdispenser/sensor'
#
@app.route('/waterdispenser/sensor', methods=['GET'])
def handle_waterdispenser_sensor_GET(request):
    cors(request, methods=['GET', 'OPTIONS'])
    return make_response(sensor, request)

#
# OPTIONS '/waterdispenser/sensor'
#
@app.route('/waterdispenser/sensor', methods=['OPTIONS'])
def handle_waterdispenser_sensor_OPTIONS(request):
    cors(request, methods=['GET', 'OPTIONS'])
    request.setHeader('Allow', 'GET, OPTIONS')