#
# Generated by xwot compiler.
#
# Type:       xwot:ContextResource
# Resource:   Valve
# Path:       /waterdispenser/valve
#

from xwot_app import app
from xwot.util.klein import make_response
from xwot.util import deserialize
from xwot.device.waterdispenser import Valve
from xwot.util.klein import cors

valve = Valve(name='Valve')

#
# GET '/waterdispenser/valve'
#
@app.route('/waterdispenser/valve', methods=['GET'])
def handle_waterdispenser_valve_GET(request):
    cors(request, methods=['GET', 'PUT'])
    return make_response(valve, request)


#
# PUT '/waterdispenser/valve'
#
@app.route('/waterdispenser/valve', methods=['PUT'])
def handle_waterdispenser_valve_PUT(request):
    data = request.content.read()
    content_type = request.getHeader('Content-Type')
    dic = deserialize(data, content_type)
    status = valve.update(dic, content_type)
    cors(request, methods=['GET', 'PUT'])
    return make_response(valve, request=request, status=status)

