#
# Generated by xwot compiler.
#
# Type:       xwot:DeviceResource
# Resource:   WaterDispenser
# Path:       /waterdispenser
#

from xwot_app import app
from xwot.util.klein import make_response
from xwot.util import deserialize
from xwot.device.waterdispenser import WaterDispenser
from xwot.util.klein import cors

waterdispener = WaterDispenser(name='Water dispenser',
                               street_address="Bd de Perolles 90 - DEPARTEMENT D'INFORMATIQUE",
                               postal_code='1700', address_locality='Fribourg', room_address='A410')

#
# GET '/waterdispenser'
#
@app.route('/waterdispenser', methods=['GET'])
def handle_waterdispenser_GET(request):
    cors(request, methods=['GET', 'PUT'])
    return make_response(waterdispener, request)

#
# PUT '/waterdispenser'
#
@app.route('/waterdispenser', methods=['PUT'])
def handle_waterdispenser_PUT(request):
    data = request.content.read()
    content_type = request.getHeader('Content-Type')
    dic = deserialize(data, content_type)
    status = waterdispener.update(dic, content_type)
    cors(request, methods=['GET', 'PUT'])
    return make_response(waterdispener, request=request, status=status)

