#
# Generated by xwot compiler.
#
# Flask xwot application.
#

import xwot_device
from xwot_device import app
from xwot.util.flask import mount_vocab

import yadp
yadp.debug()

from yadp import service
from yadp.device import Device

device = Device(urn='urn:xwot:device', url=xwot_device.http_addr, descriptions=[xwot_device.yadp_description])

service = service()
yadp.debug()
service.register(device=device, passive=True)


if __name__ == '__main__':
    mount_vocab(app, xwot_device.vocabbuilder)
    app.run(host='0.0.0.0', port=xwot_device.port, debug=True)
    service.shutdown()

