#
# Generated by xwot compiler.
#
# Flask xwot application.
#

import os
from yadp.device import Description

from xwot.util import local_ip
from xwot.util import create_description
from xwot.util.flask import hydra_link
from xwot.util.annotator import Annotator
from xwot.util.serializer import register_serializer
from xwot.util.hydra import JSONLDSerializer
from xwot.util import dir_path
from xwot.util import parent_dir_path
from xwot.util.vocabbuilder import HydraVocabBuilder


# base config
ip = local_ip()
port = 5000
http_addr = "http://%s:%s/" % (ip, port)
entry_point = http_addr + 'lightbulb'
module_dir_path = dir_path(__file__)
app_dir_path = parent_dir_path(__file__)
xwot_file = os.path.join(app_dir_path, "device.xwot")


iri = "%s%s" % (http_addr, "vocab")
vocab_url = iri + "#"
link = hydra_link(vocab_url)

annotator = Annotator()
register_serializer('application/ld+json', JSONLDSerializer(annotator))
vocabbuilder = HydraVocabBuilder(annotator)

jsonld_description_str = create_description(xwot_file=xwot_file, base=http_addr)
yadp_description = Description(content_type="application/ld+json", content=jsonld_description_str)


from flask import Flask
app = Flask(__name__)



import RootResource
import LigthbulbResource
import SensorResource

