#
# Generated by compiler compiler.
#
# Type:       xwot:Entity
# Resource:   RootResource
# Path:       /
#

from flask import Response
import xwot_device
from xwot_device import app


@app.route('/')
@xwot_device.link
def home():
    return Response(response=xwot_device.jsonld_description_str, status=200, content_type="application/ld+json")

