#
# Generated by xwot compiler.
#
# Type:       xwot:SensorResource
# Resource:   sensor
# Path:       /lightbulb/sensor
#

from flask import request
import xwot_device
from xwot_device import app
from model import IlluminanceSensor

from xwot.util.flask import make_response

sensor = IlluminanceSensor()

#
# GET '/lightbulb/sensor'
#
@xwot_device.annotator.route('sensor_get', method='GET', returns=IlluminanceSensor,
                             description="Retrieves the illuminance sensor of this lightbulb.")
@app.route('/lightbulb/sensor', methods=['GET'])
@xwot_device.link
def handle_lightbulb_sensor_GET():
    return make_response(sensor)

