#
# Generated by xwot compiler.
#
# Klein xwot application.
#
# Type:       xwot:ContextResource
# Resource:   HandleResource
# Path:       /window/handle
#

from xwot_app import app
from xwot.device.window import Handle
from xwot.util.klein import make_response
from xwot.util import deserialize
from xwot.util.klein import cors

handle = Handle(name="Window handle")

#
# GET '/window/handle'
#
@app.route('/window/handle', methods=['GET'])
def handle_window_handle_GET(request):
    cors(request, methods=['GET', 'PUT'])
    return make_response(handle, request)

#
# PUT '/window/handle'
#
@app.route('/window/handle', methods=['PUT'])
def handle_window_handle_PUT(request):
    data = request.content.read()
    content_type = request.getHeader('Content-Type')
    dic = deserialize(data, content_type)
    handle.update(dic, content_type)
    cors(request, methods=['GET', 'PUT'])
    return make_response(handle, request)

