# coding: utf-8
#
# Generated by xwot compiler.
#
# Type:       xwot:ContextResource
# Resource:   LightbulbResource
# Path:       /lightbulb
#

from flask import request
from xwot_app import app
from xwot.util.flask import make_response
from xwot.util import deserialize
from xwot.device.lightbulb import LightBulb

lightbulb = LightBulb(name='xWot LightBulb 1', street_address="Bd de Perolles 90 - DEPARTEMENT D'INFORMATIQUE",
                      postal_code='1700', address_locality='Fribourg', room_address='A410')

#
# GET '/lightbulb'
#
@app.route('/lightbulb', methods=['GET'])
def handle_lightbulb_GET():
    return make_response(lightbulb)

#
# POST '/lightbulb'
#
@app.route('/lightbulb', methods=['POST'])
def handle_lightbulb_POST():
    data = request.data
    content_type = request.headers.get('content-type')
    dic = deserialize(data, content_type)
    status = lightbulb.update(dic, content_type)

    return make_response(lightbulb, status=status)

#
# PUT '/lightbulb'
#
@app.route('/lightbulb', methods=['PUT'])
def handle_lightbulb_PUT():
    data = request.data
    content_type = request.headers.get('content-type')
    dic = deserialize(data, content_type)
    status = lightbulb.update(dic, content_type)

    return make_response(lightbulb, status=status)

