# coding: utf-8
#
# Generated by compiler compiler.
#
# Type:       xwot:Entity
# Resource:   RootResource
# Path:       /
#

import xwot_app
from xwot_app import app


@app.route('/')
def home(request):
    request.setHeader('Content-Type', 'application/ld+json')
    return xwot_app.jsonld_description_str

