# coding: utf-8
#
# Generated by xwot compiler.
#
# Type:       xwot:SensorResource
# Resource:   SensorResource
# Path:       /lightbulb/sensor
#

from xwot_app import app
from xwot.device.lightbulb import Sensor
from xwot.util.flask import make_response

sensor = Sensor()

#
# GET '/lightbulb/sensor'
#
@app.route('/lightbulb/sensor', methods=['GET'])
def handle_lightbulb_sensor_GET():
    return make_response(sensor)

