#
# Generated by xwot compiler.
#
# Flask xwot application.
#
# Type:       xwot:ContextResource
# Resource:   LockResource
# Path:       /window/lock
#

from flask import request
from xwot_app import app
from xwot.device.window import Lock
from xwot.util.flask import make_response
from xwot.util import  deserialize

lock = Lock(name="Window lock")


#
# GET '/window/lock'
#
@app.route('/window/lock', methods=['GET'])
def handle_window_lock_GET():
    return make_response(lock)

#
# PUT '/window/lock'
#
@app.route('/window/lock', methods=['PUT'])
def handle_window_lock_PUT():
    data = request.data
    content_type = request.headers.get('Content-Type')
    dic = deserialize(data, content_type)
    lock.update(dic, content_type)

    return make_response(lock)

