#
# Generated by xwot compiler.
#
# Flask xwot application.
#
# Type:       xwot:DeviceResource
# Resource:   WindowResource
# Path:       /window
#

from flask import request
from xwot_app import app
from xwot.device.window import Window
from xwot.util.flask import make_response
from xwot.util import deserialize


window = Window(name='xWoT Window', street_address="Bd de Perolles 90 - DEPARTEMENT D'INFORMATIQUE",
                postal_code='1700', address_locality='Fribourg', room_address='A410')

#
# GET '/window'
#
@app.route('/window', methods=['GET'])
def handle_window_GET():
    return make_response(window)

#
# PUT '/window'
#
@app.route('/window', methods=['PUT'])
def handle_window_PUT():
    data = request.data
    content_type = request.headers.get('Content-Type')
    dic = deserialize(data, content_type)
    window.update(dic, content_type)

    return make_response(window)

