#
# Generated by xwot compiler.
#
# Type:       xwot:DeviceResource
# Resource:   WaterDispenser
# Path:       /waterdispenser
#

from flask import request
from xwot_app import app
from xwot.util.flask import make_response
from xwot.util import deserialize
from xwot.device.waterdispenser import WaterDispenser

waterdispener = WaterDispenser(name='xWot Water dispenser',
                               street_address="Bd de Perolles 90 - DEPARTEMENT D'INFORMATIQUE",
                               postal_code='1700', address_locality='Fribourg', room_address='A410')

#
# GET '/waterdispenser'
#
@app.route('/waterdispenser', methods=['GET'])
def handle_waterdispenser_GET():
    return make_response(waterdispener)

#
# PUT '/waterdispenser'
#
@app.route('/waterdispenser', methods=['PUT'])
def handle_waterdispenser_PUT():
    data = request.data
    content_type = request.headers.get('Content-Type')
    dic = deserialize(data, content_type)
    status = waterdispener.update(dic, content_type)

    return make_response(waterdispener, status=status)

