# coding: utf-8
#
# Generated by xwot compiler.
#
# Flask xwot application.
#
# Type:       xwot:Entity
# Resource:   Entity
# Path:       /
#

from flask import Response
import xwot_app
from xwot_app import app


@app.route('/')
def home():
    return Response(response=xwot_app.jsonld_description_str, status=200, content_type="application/ld+json")

