# coding: utf-8
#
# Generated by xwot compiler.
#
# Flask xwot application.
#
# Type:       xwot:SensorResource
# Resource:   TemperatureSensorResource
# Path:       /sensing-device/temperature
#

from flask import request
from xwot_app import app
from xwot.util.flask import make_response
from model import TemperatureSensor

temperature_sensor = TemperatureSensor()


#
# GET '/sensor/temperature'
#
@app.route('/sensing-device/temperature', methods=['GET'])
def handle_sensor_temperature_GET():
    return make_response(temperature_sensor)

