#
# Generated by xwot compiler.
#
# Klein xwot application.
#
# Type:       xwot:Resource
# Resource:   DoorResource
# Path:       /door
#

from xwot.util.klein import make_response
from xwot.util import deserialize
from xwot.device.door import Door
from xwot_app import app
from xwot.util.klein import cors

door = Door(name='Door', street_address="Bd de Perolles 90 - DEPARTEMENT D'INFORMATIQUE",
            postal_code='1700', address_locality='Fribourg', room_address='A410')

#
# GET '/door'
#
@app.route('/door', methods=['GET'])
def handle_door_GET(request):
    cors(request, methods=['GET', 'PUT', 'OPTIONS'])
    return make_response(door, request)

#
# PUT '/door'
#
@app.route('/door', methods=['PUT'])
def handle_door_PUT(request):
    data = request.content.read()
    content_type = request.getHeader('Content-Type')
    dic = deserialize(data, content_type)
    door.update(dic, content_type)
    cors(request, methods=['GET', 'PUT', 'OPTIONS'])
    return make_response(door, request)

#
# OPTIONS '/door'
#
@app.route('/door', methods=['OPTIONS'])
def handle_door_OPTIONS(request):
    cors(request, methods=['GET', 'PUT', 'OPTIONS'])
    request.setHeader('Allow', 'GET, PUT, OPTIONS')


